var model = new Model(
	{
		currentPageIndex:0,
		currentPropertyIndex:0,
		currentPropertyTab:0,
		currency:"£",
		id:
		{
			nav:"nav",
			newProperty:"newProperty",
			addPropBackButton:"addPropBackButton",
			addPropAddButton:"addPropAddButton",
			backToPropertListButton:"backToPropertListButton",
			propertyDetails:"pdTab-0",
			propName:"propName",
			propertyHolder:"propertyHolder"
		}
	}
);
