var model = new Model(
	{
		currentPageIndex:0,
		currentPropertyIndex:0,
		currentPropertyTab:0,
		currentTenantTab:0,
		currentTenantIndex:0,
		currency:"£",
		id:
		{
			nav:"nav",
			newProperty:"newProperty",
			addPropBackButton:"addPropBackButton",
			addPropAddButton:"addPropAddButton",
			backToPropertListButton:"backToPropertListButton",
			propertyDetails:"pdTab-0",
			propName:"propName",
			tenantName:"tenantName",
			newTenant:"newTenant",
			tenantHolder:"tenantHolder",
			addTenantButton:"addTenantButton",
			closeAddTenantButton:"closeAddTenantButton",
			propertyHolder:"propertyHolder"
		}
	}
);
